version: '3.5'
services:
    challenge:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: challenge
        ports:
            - '${APP_PORT:-80}:8080'
        volumes:
            - '.:/var/www/html'
        networks:
            - development
        tty: true
networks:
    development:
        driver: bridge
